language: python
services:
  -docker


python:
  - "3.6"



install:
  - make deps



script:
  - make test

  

deploy:
    provider: heroku
    app: tranquil-beyond-59817
    api_key: ${HEROKU_API_KEY}
